// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```


class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCzWBJtrOY20FlWK6nWgeks9VEEP3WcAh8',
    appId: '1:268240137223:web:c1e2207a361c3be60b0ea2',
    messagingSenderId: '268240137223',
    projectId: 'authtest-e330b',
    authDomain: 'authtest-e330b.firebaseapp.com',
    storageBucket: 'authtest-e330b.appspot.com',
    measurementId: 'G-MPF1EC2203',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCEkepakybLYMkyzX-Xmvm5dRG0DWsVrcw',
    appId: '1:268240137223:android:77fc8aac56cc1e4e0b0ea2',
    messagingSenderId: '268240137223',
    projectId: 'authtest-e330b',
    storageBucket: 'authtest-e330b.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAH2_0YtPxkz_59jaCJ5DSrNiDyb726fL8',
    appId: '1:268240137223:ios:e32a87a0be5cf2860b0ea2',
    messagingSenderId: '268240137223',
    projectId: 'authtest-e330b',
    storageBucket: 'authtest-e330b.appspot.com',
    androidClientId: '268240137223-om9htu4g2unk09bqbgcqh7gtvipr8qat.apps.googleusercontent.com',
    iosClientId: '268240137223-p4mb2u9cmcbhs1kpu9ku2vuign6d0boq.apps.googleusercontent.com',
    iosBundleId: 'com.example.laboratory',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAH2_0YtPxkz_59jaCJ5DSrNiDyb726fL8',
    appId: '1:268240137223:ios:e32a87a0be5cf2860b0ea2',
    messagingSenderId: '268240137223',
    projectId: 'authtest-e330b',
    storageBucket: 'authtest-e330b.appspot.com',
    androidClientId: '268240137223-om9htu4g2unk09bqbgcqh7gtvipr8qat.apps.googleusercontent.com',
    iosClientId: '268240137223-p4mb2u9cmcbhs1kpu9ku2vuign6d0boq.apps.googleusercontent.com',
    iosBundleId: 'com.example.laboratory',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCzWBJtrOY20FlWK6nWgeks9VEEP3WcAh8',
    appId: '1:268240137223:web:f2eb3a0e2d5239c00b0ea2',
    messagingSenderId: '268240137223',
    projectId: 'authtest-e330b',
    authDomain: 'authtest-e330b.firebaseapp.com',
    storageBucket: 'authtest-e330b.appspot.com',
    measurementId: 'G-JT98HJM1K0',
  );
}
